version: '3'

vars:
  VERSION: 0.0.3
  DISTDIR: ./dist
  CHARTS: [ 'awg-demoapp' ]
  REPOSITORY: awgappdevlabs.azurecr.io

tasks:

  # logs into the ACR repository
  login-acr:
    cmds:
      - az acr login -n {{ .REPOSITORY }}

  build-awg-demoapp-caller:
    run: when_changed
    sources:
      - awg-demoapp-caller/pom.xml
      - awg-demoapp-caller/src/**/*
    generates:
      - awg-demoapp-caller/target/jib-image.tar
      - "{{ .DISTDIR }}/awg-demoapp-caller-{{ .VERSION }}.tar"
    cmds:
      - mvn -f awg-demoapp-caller/pom.xml clean compile jib:buildTar
      - cp awg-demoapp-caller/target/jib-image.tar {{ .DISTDIR }}/awg-demoapp-caller-{{ .VERSION }}.tar

  publish-awg-demoapp-caller:
    deps:
      - build-awg-demoapp-caller
    cmds:
      - crane push {{ .DISTDIR }}/awg-demoapp-caller-{{ .VERSION }}.tar {{ .REPOSITORY }}/awg-demoapp/caller:{{ .VERSION }}

  build-awg-demoapp-server:
    run: when_changed
    sources:
      - awg-demoapp-server/pom.xml
      - awg-demoapp-server/src/**/*
    generates:
      - awg-demoapp-server/target/jib-image.tar
      - "{{ .DISTDIR }}/awg-demoapp-server-{{ .VERSION }}.tar"
    cmds:
      - mvn -f awg-demoapp-server/pom.xml clean compile jib:buildTar
      - cp awg-demoapp-server/target/jib-image.tar {{ .DISTDIR }}/awg-demoapp-server-{{ .VERSION }}.tar

  publish-awg-demoapp-server:
    deps:
      - build-awg-demoapp-server
    cmds:
      - crane push {{ .DISTDIR }}/awg-demoapp-server-{{ .VERSION }}.tar {{ .REPOSITORY }}/awg-demoapp/server:{{ .VERSION }}

  # reusable task which builds a Helm chart by a name given by the CHART variable
  build-chart:
    run: when_changed
    requires:
      vars:
        - CHART
        - VERSION
    sources:
      - charts/{{ .CHART }}/**/*
    generates:
      - '{{ .DISTDIR }}/{{ .CHART }}-{{ .VERSION }}.tgz'
    preconditions:
      - test -f 'charts/{{ .CHART }}/Chart.yaml'
    cmds:
      - mkdir -p {{ .DISTDIR }}
      - helm package charts/{{ .CHART }} -d {{ .DISTDIR }} --app-version {{ .VERSION }} --version {{ .VERSION }}

  # builds all the charts
  build-charts:
    deps:
      - task: login-acr
      - for: { var: CHARTS }
        task: build-chart
        vars:
          CHART: '{{ .ITEM }}'
  
  # reusable task which publishes a Helm chart by a name given by the CHART variable
  publish-chart:
    run: when_changed
    deps:
      - task: build-chart
        vars:
          CHART: '{{ .CHART }}'
    requires:
      vars:
        - CHART
        - VERSION
    cmds:
      - helm push '{{ .DISTDIR }}/{{ .CHART }}-{{ .VERSION }}.tgz' 'oci://{{ .REPOSITORY }}/charts'

  # publishes all the charts
  publish-charts:
    deps:
      - for: { var: CHARTS }
        task: publish-chart
        vars:
          CHART: '{{ .ITEM }}'

  build:
    deps:
      - build-awg-demoapp-caller
      - build-awg-demoapp-server
      - build-charts

  publish:
    deps:
      - publish-awg-demoapp-caller
      - publish-awg-demoapp-server
      - publish-charts

  default:
    deps:
      - build
  