nameOverride: ""
fullnameOverride: ""

application:
  name: 
  metadataLocation: northcentralus
  defaultResourceLocation: southcentralus

imagePullSecrets: []
image:
  repository: awgappdevlabs.azurecr.io/awg-demoapp
  pullPolicy: IfNotPresent
  tag: ""

replicaCount: 1

podAnnotations: {}
podLabels: {}
podSecurityContext: {}

nodeSelector: {}

securityContext: {}
tolerations: []
affinity: {}

gateway:
  enabled: true
  className: ""
  annotations: {}
  hostnames: []

certificate:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: internal
