nameOverride: ""
fullnameOverride: ""

application:
  metadataLocation: northcentralus
  defaultResourceLocation: southcentralus

imagePullSecrets: []
image:
  repository: awgappdevlabs.azurecr.io/awg-demoapp
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

replicaCount: 1

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

gateway:
  enabled: false
  className: ""
  annotations: {}
  hostnames: []

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

nodeSelector: {}
tolerations: []
affinity: {}
