{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "awg-demoapp.fullname" . }}
  labels:
    {{- include "awg-demoapp.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.gateway.className }}
  gatewayClassName: {{ . }}
  {{- end }}
  {{- range .Values.gateway.hostnames }}
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    hostname: {{ . | quote }}
    allowedRoutes:
      namespaces:
        from: Same
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - name: {{ include "awg-demoapp.fullname" $ }}-tls
  {{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "awg-demoapp.fullname" . }}
  labels:
    {{- include "awg-demoapp.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ include "awg-demoapp.fullname" . }}
  hostnames:
  {{- range .Values.gateway.hostnames }}
    - {{ . | quote }}
  {{- end }}
  rules:
  - matches:
    - path:
        value: /
    filters:
    - type: RequestRedirect
      requestRedirect:
        statusCode: 302
        path:
          type: ReplaceFullPath
          replaceFullPath: /landing
  - matches:
    - path:
        type: PathPrefix
        value: /landing
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: {{ include "awg-demoapp.component.fullname" (dict "componentName" "landing" "context" $) }}
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /store-master
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: {{ include "awg-demoapp.component.fullname" (dict "componentName" "store-master" "context" $) }}
      port: 80
{{- end }}
